

export interface MoveFlags {
    contact: boolean,
    ignoreProtect: boolean,
    magicCoat: boolean,
    snatch: boolean,
    kingsrock: boolean,
    punch: boolean,
    bitting: boolean,
    pulse: boolean,
    sound: boolean,
    balistic: boolean,
    powder: boolean,
    dance: boolean,
    wind: boolean,
    slice: boolean,
    heal: boolean,
    minimizedDamage: boolean,
    ignoreAbility: boolean,
    ignoreEvasion: boolean,
    damageUnderground: boolean,
    damageUnderwater: boolean,
    damageAirborn: boolean,
    damageAirbornDouble: boolean,
    ignoreFlyUngrounded: boolean,
    thawsUser: boolean,
    ignoreSub: boolean,
    forcePressure: boolean,
    cantUseTwice: boolean,
}

export interface MoveFlagsBan {
    gravity: boolean,
    mirrorMove: boolean,
    meFirst: boolean,
    mimic: boolean,
    metronome: boolean,
    copycat: boolean,
    assist: boolean,
    sleepTalk: boolean,
    instruct: boolean,
    encore: boolean,
    parental: boolean,
    skyBattle: boolean,
    sketch: boolean,
}

export interface Move {
    NAME: string,
    name: string,
    description: string,
    effect: string,
    type: string,
    category: string,
    power: number,
    acc: number,
    target: string,
    pp: number,
    zmove: {effect: string, power: number},
    prio: number,
    recoil: number,
    strikeCount: number,
    criticalStage: number,
    alwaysCrit: boolean,
    additionnalEffect: string[],
    flags: MoveFlags,
    ban: MoveFlagsBan,
    argument: string,
}


export function initMove(): Move{
    return { 
        NAME: "",
        name: "",
        description: "",
        effect: "",
        category: "",
        type: "",
        power: 0,
        acc: 0,
        target: "",
        pp: 0,
        zmove: {effect: "", power: 0},
        prio: 0,
        recoil: 0,
        strikeCount: 1,
        criticalStage: 0,
        alwaysCrit: false,
        additionnalEffect: [],
        flags: {
            contact: false,
            ignoreProtect: false,
            magicCoat: false,
            snatch: false,
            kingsrock: false,
            punch: false,
            bitting: false,
            pulse: false,
            sound: false,
            balistic: false,
            powder: false,
            dance: false,
            wind: false,
            slice: false,
            heal: false,
            minimizedDamage: false,
            ignoreAbility: false,
            ignoreEvasion: false,
            damageUnderground: false,
            damageUnderwater: false,
            damageAirborn: false,
            damageAirbornDouble: false,
            ignoreFlyUngrounded: false,
            thawsUser: false,
            ignoreSub: false,
            forcePressure: false,
            cantUseTwice: false,
        },
        ban: {
            gravity: false,
            mirrorMove: false,
            meFirst: false,
            mimic: false,
            metronome: false,
            copycat: false,
            assist: false,
            sleepTalk: false,
            instruct: false,
            encore: false,
            parental: false,
            skyBattle: false,
            sketch: false,
        },
        argument: "",
    }
}

export interface ERMoveFlags extends MoveFlags{
    twoTurnMove: boolean,
    arrowBased: boolean,
    hornBased: boolean,
    airBased: boolean,
    hammerBased: boolean,
    throwingBased: boolean
    doubleDamageVsMega: boolean,
    recklessBoost: boolean,
    sheerForceBoost: boolean,
    statsChangeIgnored: boolean,
    strickerBoost: boolean,
    protection: boolean,
    BoneBased: boolean,
    weatherBased: boolean,
    fieldBased: boolean,
}

export interface ERMoveFlagsBan extends MoveFlagsBan{

}

export interface ERMove extends Move{
    type2: string,
    chance: number,
    splitFlag: string[],
    flags: ERMoveFlags,
    ban: ERMoveFlagsBan,
}

export function initErMove(): ERMove{
    return{
        ...initMove(),
        type2: "",
        chance: 0,
        splitFlag: [],
        flags: {
            twoTurnMove: false,
            arrowBased: false,
            hornBased: false,
            airBased: false,
            hammerBased: false,
            throwingBased: false,
            doubleDamageVsMega: false,
            contact: false,
            ignoreProtect: false,
            magicCoat: false,
            snatch: false,
            kingsrock: false,
            punch: false,
            bitting: false,
            pulse: false,
            sound: false,
            balistic: false,
            powder: false,
            dance: false,
            wind: false,
            slice: false,
            heal: false,
            minimizedDamage: false,
            ignoreAbility: false,
            ignoreEvasion: false,
            damageUnderground: false,
            damageUnderwater: false,
            damageAirborn: false,
            damageAirbornDouble: false,
            ignoreFlyUngrounded: false,
            thawsUser: false,
            ignoreSub: false,
            forcePressure: false,
            cantUseTwice: false,
            recklessBoost: false,
            sheerForceBoost: false,
            statsChangeIgnored: false,
            strickerBoost: false,
            protection: false,
            BoneBased: false,
            weatherBased: false,
            fieldBased: false
        },
        ban: {
            gravity: false,
            mirrorMove: false,
            meFirst: false,
            mimic: false,
            metronome: false,
            copycat: false,
            assist: false,
            sleepTalk: false,
            instruct: false,
            encore: false,
            parental: false,
            skyBattle: false,
            sketch: false
        }
    }
}